### PR TITLE
Updating templates to reflect new instance types (EC2 and RDS)

### PR DESCRIPTION
**Pull request by dgomesbr**
*Issue #2 , if available:*

*Description of changes:*
Closes aws-samples/aws-refarch-moodle#2 by updating the necessary files.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brianjbeach** [comment]
Apologies. It's been a crazy few weeks and I have not had time to look at this. I'll get to it by the end of the week.

**Comment by brianjbeach** [comment]
Finally had a minute. I appreciate the first two commits and would be glad to approve them. The third, moves from PSQL to MySQL. I'm open to that, but we should offer an option. Do you want to add that option or commit the new size options?

**Comment by dgomesbr** [comment]
Please, just ignore it. Looks like the original doesn't fill the user
needs. I'll do a couple other things and push later next month on several
alternatives.

**Comment by brianjbeach** [comment]
Closing as requested

**Pull request closed without merging**
